# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 23:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_specs', models.TextField(blank=True)),
                ('specs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('errors_warnings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(unique=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('model_input', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taxbrainrest.ModelInput')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelmeta',
            name='model_result',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taxbrainrest.ModelResult'),
        ),
    ]
